apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: sample-template
  title: Sample Service
  description: Create a simple template
  tags:
    - recommended
    - java
spec:
  owner: service@example.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
    properties:
      component_id:
        title: Name
        type: string
        default: sample-component
        description: Unique name of the component
      description:
        title: Description
        type: string
        default: sample-component
        description: Help others understand what this service does.
      http_port:
        title: Port
        type: integer
        default: 8080
        description: The port to run the gRPC service on
