apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    sonarqube.org/project-key: com.singtel.digital.core:logging
    jenkins.io/github-folder: test-folder/test-job
    github.com/project-slug: {{cookiecutter.storePath | jsonify}}
    backstage.io/techdocs-ref: github:https://github.com/{{cookiecutter.storePath}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}